# Compile selected Linux drivers as native Windows drivers (.SYS files)
#

# WINDOWS_ARCH ?= x86_64
WINDOWS_ARCH ?= i686
CROSS_COMPILE = $(WINDOWS_ARCH)-w64-mingw32-
SRCARCH = $(ARCH)

generated-y :=
generic-y :=
