obj-y := driver_entry.o mm.o timer.o thread.o

# KBUILD_CFLAGS += -I $(src)/include/output-$(WINDOWS_ARCH)/xdk -I $(src)/include/ddk -I $(src)/include/psdk -I $(src)/include/reactos -I $(src)/include/ndk
KBUILD_CFLAGS += -I $(src)/include/output-i686/xdk -I $(src)/include/ddk -I $(src)/include/psdk -I $(src)/include/reactos -I $(src)/include/ndk -I $(src)/include/crt
