obj-y += process.o irq.o ptrace.o proc.o jiffies.o reboot.o mem.o setup.o dumpstack.o time.o sched.o

extra-y := vmlinux.lds

KBUILD_CFLAGS += -I $(src)/include/output-i686/xdk -I $(src)/include/ddk -I $(src)/include/psdk -I $(src)/include/reactos -I $(src)/include/ndk -I $(src)/include/crt

